### ISSUE TITLE
Pom files not generated for flavors

### ISSUE THREAD

**Issue by shanethmoore** [dimensionv/androdialogs#1]
Question: I'm facing the same problem you had a while back where you couldn't generate pom files for different flavors for an Android library project. You referenced your androDialogs project here. 

Did you ever manage to figure out how to generate the poms for flavors?

**Comment by dimensionv** [comment]
No, it's still not working. I am currenlty doing a nasty work around, uploading everything to sonatype using ./gradlew uploadArchives, download everything again and then bundle it into separate zips per flavor, adding the pom.xml to each zip. Then I upload the zip manually as bundle to sonatype's nexus and release it. It seems there's no other way, and so far it seems that no one cares enough to fix it. I have no idea how to fix it myself, properly, sorry. It's tedious, nasty and ugly... :(

**Comment by shanethmoore** [comment]
:skull: Thats unfortunate mate. Thanks for getting back so quick. Hopefully the tool chain gets better and the new [publishing](https://docs.gradle.org/current/dsl/org.gradle.api.publish.PublishingExtension.html) mechanism turns into something usable.

Cheers
